title: DLink De-Cryptor
email: ikerin@gmail.com
description: >-
  Decrypt the backup config.xml file from DLink routers, to extract the PPPoE password
baseurl: "/ddecryptor"
url: "https://ivank.github.io"
github_username: ivank

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
